on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release
        with:
          token: ${{ secrets.RELEASE }}

      - name: Add File to Release (blueprint/yacc)
        id: add_blueprint
        if: ${{ steps.release.outputs['blueprint/yacc--release_created'] }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}
          tag: ${{ steps.release.outputs.tag_name }}
        run: |
          gh release upload $tag blueprint/yacc/yacc.yaml LICENSE
